enum ACTION {
  // HEADER
  LOGOUT = "LOGOUT",
  // Account
  SET_ACCOUNT_CATEGORY = "SET_ACCOUNT_CATEGORY",
  // Manage
  POST_CATEGORY = "POST_CATEGORY",
  POST_PRODUCT = "POST_PRODUCT",

  UPD_CATEGORY_FIELD_TITLE = "UPD_CATEGORY_FIELD_TITLE",
  UPD_PRODUCT_FIELD_TITLE = "UPD_PRODUCT_FIELD_TITLE",
  UPD_NUM_OF_TEXT_FIELDS = "UPD_NUM_OF_TEXT_FIELDS",
  UPD_PERSONAL_DATA_FORM_TITLE = "UPD_PERSONAL_DATA_FORM_TITLE",
  // History
  DELETE_CATEGORY = "DELETE_CATEGORY",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  // Catalog
  SET_CATALOG_CATEGORY = "SET_CATALOG_CATEGORY",
  ADD_TO_BAG = "ADD_TO_BAG",

  ADD_CATEGORY = "ADD_CATEGORY",
  ADD_PRODUCT = "ADD_PRODUCT",

  REMOVE_CATEGORY = "REMOVE_CATEGORY",
  REMOVE_PRODUCT = "REMOVE_PRODUCT",

  // Bag
  REMOVE_FROM_BAG = "REMOVE_FROM_BAG",
  UPD_QTY_FIELD = "UPD_QTY_FIELD",
  UPD_INFO_FORM_FIELD = "UPD_INFO_FORM_FIELD",

  // Login
  UPD_LOGIN_FORM_VALUE = "UPD_LOGIN_FORM_VALUE",
  LOGIN = "LOGIN",
  SET_AUTHENTIFICATION = "SET_AUTHENTIFICATION",

  // Sign Up
  UPD_SIGN_UP_FORM_VALUE = "UPD_SIGN_UP_FORM_VALUE",
  UPD_SIGN_UP_CHECK_BOX_VALUE = "UPD_SIGN_UP_CHECK_BOX_VALUE",
  POST_USER = "POST_USER",

  // REQUESTS
  SEND_REQUEST = "SEND_REQUEST",
  GET_REQUEST = "GET_REQUEST",

  GET_CATEGORIES_AND_PRODUCTS = "GET_CATEGORIES_AND_PRODUCTS",
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_PRODUCTS = "GET_PRODUCTS",
  SET_CATEGORIES = "SET_CATEGORIES",
  SET_PRODUCTS = "SET_PRODUCTS",

  DID_FETCH_CATEGORIES = "DID_FETCH_CATEGORIES",

  SET_USER = "SET_USER",

  GET_USER = "GET_USER",
  LOGIN_ERROR = "LOGIN_ERROR",
}

export default ACTION;
