"""empty message

Revision ID: 003ebaf9e1cd
Revises: 96549f134cc8
Create Date: 2020-08-25 21:46:59.826519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003ebaf9e1cd'
down_revision = '96549f134cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('category', 'creationDate')
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=True)
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'bag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bag', sa.BLOB(), nullable=False))
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'password')
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('category', sa.Column('creationDate', sa.DATETIME(), nullable=False))
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
