"""empty message

Revision ID: 318d4052dc70
Revises: 448f67ac4069
Create Date: 2020-09-08 10:35:37.861314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318d4052dc70'
down_revision = '448f67ac4069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costs', sa.PickleType(), nullable=True),
    sa.Column('quantities', sa.PickleType(), nullable=True),
    sa.Column('info', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('canAddCategory', sa.Boolean(), nullable=True),
    sa.Column('canAddProduct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('creationDate', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('specs', sa.PickleType(), nullable=True),
    sa.Column('values', sa.PickleType(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('extra_info', sa.String(length=500), nullable=True),
    sa.Column('creationDate', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bags',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('demands',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    op.drop_table('bags')
    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('user')
    op.drop_table('demand')
    # ### end Alembic commands ###
