"""empty message

Revision ID: 448f67ac4069
Revises: e61e76a4d163
Create Date: 2020-09-04 13:37:04.040484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448f67ac4069'
down_revision = 'e61e76a4d163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costs', sa.PickleType(), nullable=True),
    sa.Column('quantities', sa.PickleType(), nullable=True),
    sa.Column('info', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demands',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    op.drop_table('demand')
    # ### end Alembic commands ###
