"""empty message

Revision ID: 52e0ae34c80a
Revises: 318d4052dc70
Create Date: 2020-09-08 10:37:30.230769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e0ae34c80a'
down_revision = '318d4052dc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('creationDate', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('specs', sa.PickleType(), nullable=True),
    sa.Column('values', sa.PickleType(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('extra_info', sa.String(length=500), nullable=True),
    sa.Column('creationDate', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bags',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('demands',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    op.drop_table('bags')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
