"""empty message

Revision ID: 96549f134cc8
Revises: 72757920f37c
Create Date: 2020-08-25 21:44:46.865408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96549f134cc8'
down_revision = '72757920f37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=True)
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'bag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bag', sa.BLOB(), nullable=False))
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'password')
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('category', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
