"""empty message

Revision ID: a73e548c5150
Revises: 198de096dfcd
Create Date: 2020-08-25 21:41:10.928854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73e548c5150'
down_revision = '198de096dfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=True)
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'bag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bag', sa.BLOB(), nullable=False))
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'canAddProduct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'canAddCategory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'password')
    op.alter_column('product', 'values',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'specs',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('category', 'creationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
