"""empty message

Revision ID: ff378b898dd4
Revises: 976856ad9c3a
Create Date: 2020-08-25 21:37:58.639617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff378b898dd4'
down_revision = '976856ad9c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=False))
    op.drop_column('user', 'bag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bag', sa.BLOB(), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
